name: ci
"on":
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
env:
    REGISTRY: ghcr.io
    IMAGE_NAME: "${{ github.repository }}"
jobs:
    turbo-build:
        runs-on: ubuntu-latest
        outputs:
            matrix: ${{ steps.turbo-build.outputs.apps }}
        steps:
            - name: Check out code
              uses: actions/checkout@v4
            - name: Cache turbo build setup
              uses: actions/cache@v4
              with:
                  path: .turbo
                  key: "${{ runner.os }}-turbo-${{ github.sha }}"
                  restore-keys: |
                      ${{ runner.os }}-turbo-
            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: npm
            - name: Install dependencies
              run: npm ci
            - name: Build
              id: turbo-build
              run: |
                  rm -rf .turbo/cache
                  mkdir -p .logs
                  npm run build > .logs/turbo.log 2>&1
                  echo "Turbo build output:"
                  cat .logs/turbo.log

                  APPS=$(grep -oE 'apps/[^ ]+' .logs/turbo.log | sort -u)

                  echo "Apps that had a cache miss:"
                  echo "$APPS"
                    
                  # Build compact JSON array
                  JSON_ARRAY=$(printf '['; printf '"%s",' $APPS | sed 's/,$//'; printf ']')

                  # Export it cleanly without breaking GitHub's format
                  echo "apps=${JSON_ARRAY}" >> "$GITHUB_OUTPUT"
                  echo "apps=${JSON_ARRAY}"
    docker-build:
        needs: turbo-build
        runs-on: ubuntu-latest
        if: ${{ needs.turbo-build.outputs.matrix != '[]' }}
        strategy:
            matrix:
                app: ${{ fromJson(needs.turbo-build.outputs.matrix) }}
        steps:
            - name: Format app name
              id: format-app-name
              run: |
                  FORMATTED_APP=$(echo ${{ matrix.app }} | awk -F'/' '{print $2"-"$1}')
                  echo "formatted_app=${FORMATTED_APP}" >> "$GITHUB_OUTPUT"
                  echo "formatted_app=${FORMATTED_APP}"
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Docker Buildx for ${{ matrix.app }}
              uses: docker/setup-buildx-action@v3
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.REGISTRY }}/${{ steps.format-app-name.outputs.formatted_app }}
                  flavor: |
                      latest=auto
                      prefix=
                      suffix=
                  tags: |
                      type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
                      type=sha,prefix=,format=long
            - name: Build and push the Docker image for ${{ matrix.app }}
              uses: docker/build-push-action@v5
              with:
                  context: ${{ matrix.app }}
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
